# permissions for end users to edit automations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: automation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ocf-operator
    app.kubernetes.io/part-of: ocf-operator
    app.kubernetes.io/managed-by: kustomize
  name: automation-editor-role
rules:
- apiGroups:
  - iot.iot.dev
  resources:
  - automations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.iot.dev
  resources:
  - automations/status
  verbs:
  - get
