---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - iot.iot.dev
  resources:
  - ocfdeviceboardings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.iot.dev
  resources:
  - ocfdeviceboardings/finalizers
  verbs:
  - update
- apiGroups:
  - iot.iot.dev
  resources:
  - ocfdeviceboardings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iot.iot.dev
  resources:
  - ocfdeviceresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.iot.dev
  resources:
  - ocfdeviceresources/finalizers
  verbs:
  - update
- apiGroups:
  - iot.iot.dev
  resources:
  - ocfdeviceresources/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - iot.iot.dev
  resources:
  - ocfdevices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iot.iot.dev
  resources:
  - ocfdevices/finalizers
  verbs:
  - update
- apiGroups:
  - iot.iot.dev
  resources:
  - ocfdevices/status
  verbs:
  - get
  - patch
  - update
