apiVersion: iot.iot.dev/v1alpha1
kind: Automation
metadata:
  labels:
    app.kubernetes.io/name: automation
    app.kubernetes.io/instance: automation-sample
    app.kubernetes.io/part-of: ocf-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ocf-operator
  name: automation-sample
spec:
  trigger:
    inputtype: Numeric
    ondevice: 332076de-754e-46a7-6e6c-d3ad734b32ac
    forresource: /temperature
    max: 20
    min: 19
    period:
      hours: 1
      minutes: 3
      seconds: 10
  action:
    - type: Message
      data: 
        - message: "Temperature threshold trigger"
          email: "vitumafeni@dcn.ssu.ac.kr"
    - type: Event 
      data:
        - targetdevice: 332076de-754e-46a7-6e6c-d3ad734b32ac
          targetresource: /switch1
          value: true
          period:
            hours: 1
          
